"""changed answer model

Revision ID: 11a150a146a8
Revises: 04d67f933d19
Create Date: 2023-03-28 14:12:36.758264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "11a150a146a8"
down_revision = "04d67f933d19"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answers", "is_correct")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answers",
        sa.Column(
            "is_correct", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
