"""add relation table game question

Revision ID: 3eb4a2e47767
Revises: 11a150a146a8
Create Date: 2023-03-28 14:34:07.153814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3eb4a2e47767"
down_revision = "11a150a146a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
