"""add auto datetime

Revision ID: b86f26160e3b
Revises: c46d4cdb4dbe
Create Date: 2023-03-16 13:40:39.074563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b86f26160e3b"
down_revision = "c46d4cdb4dbe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
