"""add field in question model

Revision ID: d7658d797f7b
Revises: 3eb4a2e47767
Create Date: 2023-03-31 21:53:22.628122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d7658d797f7b"
down_revision = "3eb4a2e47767"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "gamescores", "players", ["player_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "questions", sa.Column("accepted", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "accepted")
    op.drop_constraint(None, "gamescores", type_="foreignkey")
    # ### end Alembic commands ###
