"""move comments from answer to question

Revision ID: e1fc3003f06a
Revises: adb7c669880e
Create Date: 2023-04-12 19:48:55.217842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e1fc3003f06a"
down_revision = "adb7c669880e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answers", "comments")
    op.add_column(
        "questions", sa.Column("comments", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "comments")
    op.add_column(
        "answers",
        sa.Column("comments", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
