"""add relationships in GSModel

Revision ID: fa5463fff603
Revises: 1738f0a231fc
Create Date: 2023-03-15 18:01:56.621946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa5463fff603"
down_revision = "1738f0a231fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
